################################# Default configuration ###################
# provide your domain here
baseURL = "https://docs.lexgate.ch"
# theme
theme = "dot-hugo"
assetDir = "assets"
# site title
title = "Lexgate Documentation"
# disable language
disableLanguages = []
# google analytics
googleAnalytics = "" # paste your analytics ID here. (Ex: UA-123-45)
# unsafe html
[markup.goldmark.renderer]
unsafe = true


############################# Default Parameters ##########################
[params]
# logo is for all page
logo = ""
# logo white is for homepage logo, you can use colorful logo too...
logo_white = ""
# when logo is empty, it will shown your site title

# customize color
primary_color = "#db2828"
body_color = "#f9f9f9"
text_color = "#636363"
text_color_dark = "#242738"
white_color = "#ffffff"
light_color = "#f8f9fa"

# font family
font_family = "lato" # Choose font family from : https://fonts.google.com/

# contact form action
contact_form_action = "#" # contact form works with : https://formspree.io


############################## social links ##############################
  
[[params.social]]
icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
link = "https://www.linkedin.com/company/lextira/"

################################ English Language ######################
[Languages.en]
languageName = "EN"
languageCode = "en-us"
weight = 1
copyright = "Copyright by Lextira"

# banner
[Languages.en.params.banner]
title = "Lexgate Documentation"
subtitle = ""
bg_image = "images/shunya-koide-VRnqu6UWUFY-unsplash.jpg"
placeholder = "Search in this documentation..."

# call to action
[Languages.en.params.cta]
enable = false
title = "Didn't find an answer to your question?"
content = ""
# call to action button
[Languages.en.params.cta.button]
enable = true
label = "contact us"
link = "contact"


################## english navigation #################
[[Languages.en.menu.main]]
name = "Home"
url = "/"
weight = 1

# Dropdown menu
[[Languages.en.menu.main]]
weight = 2
name = "Documentation"
hasChildren = true

  [[Languages.en.menu.main]]
  parent = "Documentation"
  name = "Contact Management"
  url = "contact-management"
  weight = 1

  [[Languages.en.menu.main]]
  parent = "Documentation"
  name = "Document Management"
  url = "document-management"
  weight = 2

  [[Languages.en.menu.main]]
  parent = "Documentation"
  name = "Project Management"
  url = "project-management"
  weight = 3

  [[Languages.en.menu.main]]
  parent = "Documentation"
  name = "Project Creation"
  url = "project-creation"
  weight = 4


[[Languages.en.menu.main]]
name = "API"
url = "https://docs.lexgate.ch/api"
weight = 3


################################### German Language ######################
[Languages.de]
languageName = "DE"
languageCode = "de-ch"
weight = 2
copyright = "Copyright by Lextira"

# banner
[Languages.de.params.banner]
title = "Lexgate Dokumentation"
subtitle = ""
bg_image = "images/shunya-koide-VRnqu6UWUFY-unsplash.jpg"
placeholder = "In dieser Dokumentation suchen..."


################## german navigation #################
[[Languages.de.menu.main]]
name = "Home"
url = "/"
weight = 1

# Dropdown menu
[[Languages.de.menu.main]]
weight = 2
name = "Dokumentation"
hasChildren = true

  [[Languages.de.menu.main]]
  parent = "Dokumentation"
  name = "Kontaktverwaltung"
  url = "contact-management"
  weight = 1

  [[Languages.de.menu.main]]
  parent = "Dokumentation"
  name = "Dokumentverwaltung"
  url = "document-management"
  weight = 2

  [[Languages.de.menu.main]]
  parent = "Dokumentation"
  name = "Projektverwaltung"
  url = "project-management"
  weight = 3

  [[Languages.de.menu.main]]
  parent = "Dokumentation"
  name = "Projekterfassung"
  url = "project-creation"
  weight = 4


[[Languages.de.menu.main]]
name = "API"
url = "https://docs.lexgate.ch/api"
weight = 3